# Generated by Django 6.1.1 on 2026-09-20 06:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basic', 'Basic check-up'), ('standard', 'Standard service'), ('full', 'Full refurbishment')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Price in INR')),
                ('description', models.TextField(blank=True)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Renders as the featured card on the pricing grid.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 220+', max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(default='Bengaluru', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vehicles.servicepackage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('brand', models.CharField(db_index=True, max_length=60)),
                ('model_name', models.CharField(max_length=80, verbose_name='Model')),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('type', models.CharField(choices=[('Scooter', 'Scooter'), ('Motorcycle', 'Motorcycle')], db_index=True, max_length=12)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980)], verbose_name='Model year')),
                ('km', models.PositiveIntegerField(verbose_name='Kilometres run')),
                ('owners', models.CharField(choices=[('1st owner', '1st owner'), ('2nd owner', '2nd owner'), ('3rd owner or more', '3rd owner or more')], default='1st owner', max_length=40)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Electric', 'Electric')], default='Petrol', max_length=30)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('registration', models.CharField(blank=True, help_text='e.g. KA-05', max_length=20)),
                ('price', models.PositiveIntegerField(help_text='Listing price in INR')),
                ('original_price', models.PositiveIntegerField(blank=True, help_text='Market value before discount. Leave blank when not discounted.', null=True)),
                ('emi', models.PositiveIntegerField(default=0, help_text='Estimated monthly EMI in INR. Auto-calculated when 0.')),
                ('city', models.CharField(db_index=True, default='Bengaluru', max_length=80)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('tier', models.CharField(choices=[('Certified', 'Certified'), ('Verified', 'Verified'), ('Direct', 'Direct')], db_index=True, default='Direct', max_length=12)),
                ('warranty', models.BooleanField(default=False, verbose_name='Warranty included')),
                ('free_service', models.BooleanField(default=False, verbose_name='Free service included')),
                ('demand', models.CharField(choices=[('High', 'High — selling fast'), ('Moderate', 'Moderate — selling steadily'), ('Low', 'Low — slow moving')], default='Moderate', max_length=10)),
                ('sold_last_month', models.PositiveIntegerField(default=0, help_text='How many similar vehicles sold recently.')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], db_index=True, default='available', max_length=10)),
                ('is_approved', models.BooleanField(default=True, help_text='Uncheck to hide a listing from the public site.')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, help_text='Blank for dealer-owned stock managed from the admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price'], name='vehicles_ve_price_da359f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-created_at'], name='vehicles_ve_created_bb2812_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_approved', 'status'], name='vehicles_ve_is_appr_5e6cc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'vehicle'), name='unique_user_vehicle_favorite'),
        ),
    ]
